// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXPL6TgKnnVGAuUsSQn0an6SibQZJu8w4',
    appId: '1:657515213549:web:dec84e52c098fc21b892e4',
    messagingSenderId: '657515213549',
    projectId: 'eco-customer-app-7d6c1',
    authDomain: 'eco-customer-app-7d6c1.firebaseapp.com',
    storageBucket: 'eco-customer-app-7d6c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALGaYzew3Z5o6DdU1BWRAP4l6n2VeAiLQ',
    appId: '1:657515213549:android:e602137288df3caab892e4',
    messagingSenderId: '657515213549',
    projectId: 'eco-customer-app-7d6c1',
    storageBucket: 'eco-customer-app-7d6c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6DS3jWKYruZgjdDo7bBMgJM0s5gS2YOI',
    appId: '1:657515213549:ios:6bcbdbfa72f30da8b892e4',
    messagingSenderId: '657515213549',
    projectId: 'eco-customer-app-7d6c1',
    storageBucket: 'eco-customer-app-7d6c1.firebasestorage.app',
    iosBundleId: 'com.example.ecoCustomerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6DS3jWKYruZgjdDo7bBMgJM0s5gS2YOI',
    appId: '1:657515213549:ios:6bcbdbfa72f30da8b892e4',
    messagingSenderId: '657515213549',
    projectId: 'eco-customer-app-7d6c1',
    storageBucket: 'eco-customer-app-7d6c1.firebasestorage.app',
    iosBundleId: 'com.example.ecoCustomerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXPL6TgKnnVGAuUsSQn0an6SibQZJu8w4',
    appId: '1:657515213549:web:a6e1120e97920c53b892e4',
    messagingSenderId: '657515213549',
    projectId: 'eco-customer-app-7d6c1',
    authDomain: 'eco-customer-app-7d6c1.firebaseapp.com',
    storageBucket: 'eco-customer-app-7d6c1.firebasestorage.app',
  );
}
